# Generated by Django 2.2.28 on 2023-03-01 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('url_slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('icon', models.ImageField(upload_to='team_profile_images')),
                ('bio', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('url_slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('avatar', models.ImageField(null=True, upload_to='profile_images')),
                ('bio', models.CharField(max_length=1024)),
                ('support_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gutigers.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gutigers.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('venue', models.CharField(max_length=128)),
                ('home_score', models.PositiveSmallIntegerField(null=True)),
                ('away_score', models.PositiveSmallIntegerField(null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gutigers.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gutigers.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=128)),
                ('owned_teams', models.ManyToManyField(to='gutigers.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gutigers.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=4096)),
                ('rating', models.BigIntegerField(default=0)),
                ('about_match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gutigers.Match')),
                ('replies_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gutigers.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutigers.UserProfile')),
            ],
        ),
    ]
