# Generated by Django 2.1.5 on 2023-03-24 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=4096)),
                ('rating', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.BooleanField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutigers.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=128)),
                ('home_score', models.PositiveSmallIntegerField(null=True)),
                ('away_score', models.PositiveSmallIntegerField(null=True)),
                ('home_diff_away_score', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('body', models.CharField(max_length=16384)),
                ('post_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('url_slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('icon', models.ImageField(upload_to='team_profile_images')),
                ('bio', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('url_slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('bio', models.CharField(max_length=1024)),
                ('support_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gutigers.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gutigers.Team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gutigers.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gutigers.Team'),
        ),
        migrations.AddField(
            model_name='manager',
            name='owned_teams',
            field=models.ManyToManyField(to='gutigers.Team'),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gutigers.UserProfile'),
        ),
        migrations.AddField(
            model_name='commentvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutigers.UserProfile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='about_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gutigers.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replies_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gutigers.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutigers.UserProfile'),
        ),
    ]
